name: Monitoramento de Vagas

on:
  schedule:
    - cron: '0 11 * * *' # Todo dia às 08:00 AM (Horário de Brasília)
  workflow_dispatch:

jobs:
  job-hunt:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para salvar o CSV no repositório

    steps:
    - name: Checkout Código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar Dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar Scraper
      run: python scripts/scraper.py

    - name: Salvar Dados no Repositório
      run: |
        git config --global user.name "Automation Bot"
        git config --global user.email "bot@github.com"
        git add data/vagas.csv
        git commit -m "Update: Novas vagas [$(date +'%d/%m/%Y')]" || exit 0
        git push